import type { Participant } from "./types";

export const initialParticipants: Participant[] = [
  // 1
  {
    id: 1,
    name: "Muhammad Mehdi Hassan",
    role: "Leader",
    team: "Core",
    level: "Lead",
    campus: "BZU",
    responsibilities: "Overall leadership and strategic direction of the AWS Student Club at BZU.",
    image: "/images/AWS-MembersPics/Mehdi Hassan.jpeg",
  },

  // 2
  {
    id: 2,
    name: "Mirza Zaryab",
    role: "Vice Leader",
    team: "Core",
    level: "Core",
    points: 52.13636364,
    campus: "BZU",
    responsibilities: "Assisting the leader in managing club activities, coordinating between teams, and ensuring smooth operations.",
    image: "/images/AWS-MembersPics/Zaryab.jpeg",
  },

  // 3
  {
    id: 3,
    name: "Hamid Ali",
    role: "Executive Leader",
    team: "Core",
    level: "Core",
    points: 66.200,
    campus: "MNS-UET",
    responsibilities: "Overseeing daily operations and ensuring the club runs smoothly.",
    image: "/images/AWS-MembersPics/Hamid Ali.jpg",
  },

  // 4
  {
    id: 4,
    name: "Ali Sachal",
    role: "Community Manager",
    team: "Core",
    level: "Core",
    points: 59.59090909,
    campus: "BZU",
    responsibilities: "Managing and growing the club's community engagement.",
    image: "/images/AWS-MembersPics/Ali Sachal.png",
  },

  // 5
  {
    id: 5,
    name: "Ali Hassan",
    role: "Directorate of Media, Design & Marketing",
    team: "Core",
    level: "Core",
    points: 64.54545455,
    campus: "BZU",
    responsibilities: "Leading the Media, Design & Marketing team to create engaging content and promote the club's activities.",
    image: "/images/AWS-MembersPics/Ali-Hassan.jpeg",
  },

 {
    id: 6,
    name: "Hammad Ahmad",
    role: "Directorate of Events & Operations",
    team: "Core",
    level: "Core",
    points: 58.68181818,
    campus: "BZU",
    responsibilities: "Overseeing event planning and execution, as well as managing day-to-day operations.",
    image: "/images/AWS-MembersPics/Hammad Ahmad.jpg",
  },

  {
    id: 7,
    name: "Bushra Kanooz Khan",
    role: "Associate Director Design",
    team: "Media & Design",
    level: "Core",
    points: 56.68181818,
    campus: "BZU",
    responsibilities: "Assisting in leading the Media & Design team, focusing on creating visual content and designs for the club.",
    image: "/images/AWS-MembersPics/Bushra.jpeg",
  },
  {
    id: 8,
    name: "Muhammad Bin Iftikhar",
    role: "Member",
    team: "Technical",
    level: "Builder",
    points: 54.23636364,
    campus: "BZU",
    responsibilities: "Contributing to various tasks across teams as needed.",
    image: "/images/AWS-MembersPics/Muhammad.png",
  },


  {
    id: 9,
    name: "Aqib Hussain",
    role: "DevOps Leader",
    team: "Technical",
    level: "Developer",
    points: 59.14545455,
    campus: "BZU",
    responsibilities: "Cloud Development & DevOps",
    image: "/images/AWS-MembersPics/Aqib.jpg",
  },

  {
    id: 10,
    name: "Ehsan Ur Rehman",
    role: "Member",
    team: "Media & Design",
    level: "Builder",
    points: 47.72727273,
    campus: "BZU",
    responsibilities: "Marketing and Promotions",
    image: "/images/AWS-MembersPics/Muhammad Ehsan Ur Rehman.jpeg",
  },
  {
    id: 11,
    name: "Aleena Khan",
    role: "Frontend Lead",
    team: "Technical",
    level: "Developer",
    points: 47.63636364,
    campus: "BZU",
    responsibilities: "Frontend Development",
    image: "/images/AWS-MembersPics/Aleena.jpg",
  },

  {
    id: 12,
    name: "Noor Ul Ain Fatima",
    role: "Operations Manager",
    team: "Operations",
    level: "Core",
    points: 59.04545455,
    campus: "BZU",
    responsibilities: "Overseeing daily operations and ensuring the club runs smoothly.",
    image: "/images/AWS-MembersPics/Noor.jpg",
  },

  {
    id: 13,
    name: "Affan Ali",
    role: "Assistant Event Director (M)",
    team: "Events",
    level: "Builder",
    points: 58.500,
    campus: "BZU",
    responsibilities: "Event Coordination",
    image: "/images/AWS-MembersPics/Affan.jpg",
  },

  {
    id: 14,
    name: "Hoor Fatima",
    role: "Assistant Event Director (F)",
    team: "Events",
    level: "Builder",
    points: 56.04545455,
    campus: "BZU",
    responsibilities: "Event Coordination",
    image: "/images/AWS-MembersPics/Hoor.png",
  },


  {
    id: 15,
    name: "Abdul Saboor",
    role: "Senior Event Coordinator",
    team: "Events",
    level: "Builder",
    points: 59.59090909,
    campus: "BZU",
    responsibilities: "Event Management",
    image: "/images/AWS-MembersPics/Abdul Saboor.jpeg",
  },

  {
    id: 16,
    name: "Hania Amjad",
    role: "Senior Media Coordinator",
    team: "Media & Design",
    level: "Builder",
    points: 59.000,
    campus: "BZU",
    responsibilities: "Coordinating Media & Content creation for the club.",
    image: "/images/AWS-MembersPics/Hania Amjad.png",
  },

  {
    id: 17,
    name: "Moazam Ali",
    role: "Assistant Marketing Manager",
    team: "Marketing",
    level: "Builder",
    points: 58.72727273,
    campus: "BZU",
    responsibilities: "Marketing and Promotions",
    image: "/images/AWS-MembersPics/Moazam Ali.png",
  },

  {
    id: 18,
    name: "Anbreen Akhtar",
    role: "Member",
    team: "Operations",
    level: "Builder",
    points: 0.000,
    campus: "BZU",
    responsibilities: "Operations Support and Coordination",
    image: "/images/AWS-MembersPics/Ambreen.jpeg",
  },
  {
    id: 19,
    name: "Muhammad Rizwan",
    role: "Backend Developer(Member)",
    team: "Technical",
    level: "Builder",
    points: 0.000,
    campus: "BZU",
    responsibilities: "Backend Development",
    image: "/images/AWS-MembersPics/Rizwan.jpeg",
  },
  {
    id: 20,
    name: "Mujahid Javaid",
    role: "Member",
    team: "Marketing",
    level: "Builder",
    points: 0.000,
    campus: "BZU",
    responsibilities: "Community Growth & marketing",
    image: "/images/AWS-MembersPics/Mujahid.jpeg",
  }, 
  {
    id: 21,
    name: "Uzair",
    role: "Member",
    team: "Marketing",
    level: "Builder",
    points: 0.000,
    campus: "BZU",
    responsibilities: "Outreach and Promotions",
    image: "/images/AWS-MembersPics/Uzair.jpeg",
  },
  {
    id: 22,
    name: "Saim Bin Zahid",
    role: "Member",
    team: "Media & Design",
    level: "Builder",
    points: 0.000,
    campus: "BZU",
    responsibilities: "Content Creation",
    image: "/images/AWS-MembersPics/Saim.jpeg",
  },

  {
    id: 23,
    name: "Muhammad Zohaib",
    role: "Member",
    team: "Marketing",
    level: "Builder",
    points: 0.000,
    campus: "BZU",
    responsibilities: "Promotions",
    image: "/images/AWS-MembersPics/Zohaib.jpeg",
  },

  {
    id: 24,
    name: "Muzammil Shahdab",
    role: "AI Engineer(Member)",
    team: "Technical",
    level: "Builder",
    points: 0.000,
    campus: "BZU",
    responsibilities: "AI Engineering and Research",
    image: "/images/AWS-MembersPics/Muzammil Shahdab.jpg",
  },
];

export const gradients = [
  "linear-gradient(135deg,#a855f7,#312e81)",
  "linear-gradient(135deg,#7c3aed,#0f172a)",
  "linear-gradient(135deg,#c084fc,#581c87)",
  "linear-gradient(135deg,#8b5cf6,#111827)",
  "linear-gradient(135deg,#d946ef,#4338ca)",
];